version: '3.8'

services:
  maxshow-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxshow_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=official.maxshow@gmail.com
      - SMTP_PASSWORD=cbnbbcisclsagrfi
    volumes:
      - ./Backend/uploads:/app/Backend/uploads
      - ./Backend/maxshow.db:/app/Backend/maxshow.db
