/**
 * Constants & Fallback Data for MAXSHOW
 */

export const LOCATIONS = [
  'Pimpri',
  'Chinchwad',
  'Hinjawadi',
  'Punawale',
  'Kasarwadi',
  'Nigdi',
  'Aundh',
];

export const FALLBACK_EVENTS = {
  'moonlight-picnic': {
    id: 1,
    slug: 'moonlight-picnic',
    title: 'Moonlight picnic & vinyl',
    type: 'Outdoors',
    venue: 'Skyline Terrace · Hinjawadi',
    time: 'Tonight, 8:00 PM',
    location: 'Hinjawadi, Pune',
    price: 499,
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=85',
    description: 'An open-air evening under string lights with curated vinyl records, artisan picnic bites, and golden sunset views across Hinjawadi.',
    category: 'outdoors',
    day: 'today',
    rating: 4.8,
    rating_count: 42,
  },
  'blue-room': {
    id: 2,
    slug: 'blue-room',
    title: 'Blue room: acoustic night',
    type: 'Live music',
    venue: 'The Blue Room · Kasarwadi',
    time: 'Friday, 7:30 PM',
    location: 'Kasarwadi, Pimpri-Chinchwad',
    price: 399,
    image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=85',
    description: 'Settle into an intimate evening of unplugged originals, soft lights, and a carefully curated local line-up. Come early, grab a seat, and discover a new favourite voice.',
    category: 'music',
    day: 'today',
    rating: 4.0,
    rating_count: 1,
  },
  'comedy-room': {
    id: 3,
    slug: 'comedy-room',
    title: 'After hours: a comedy room',
    type: 'Comedy',
    venue: 'Laugh Lane · Nigdi',
    time: 'Saturday, 8:00 PM',
    location: 'Nigdi, Pimpri-Chinchwad',
    price: 299,
    image: 'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85',
    description: 'A relaxed late-night set featuring sharp new comics and seasoned crowd favourites. Bring friends, enjoy the room, and expect a few surprises.',
    category: 'comedy',
    day: 'weekend',
    rating: 4.7,
    rating_count: 19,
  },
  'watercolour': {
    id: 4,
    slug: 'watercolour',
    title: 'Watercolour in the park',
    type: 'Creative workshop',
    venue: 'Open Studio · Aundh',
    time: 'Sunday, 11:00 AM',
    location: 'Aundh, Pune',
    price: 450,
    image: 'https://images.unsplash.com/photo-1545987796-200677ee1011?auto=format&fit=crop&w=1200&q=85',
    description: 'A slow Sunday workshop for beginners and curious painters. Materials, guidance, and a warm cup of chai are included—just bring your favourite idea.',
    category: 'create',
    day: 'weekend',
    rating: 4.9,
    rating_count: 15,
  },
  'rooftop-cinema': {
    id: 5,
    slug: 'rooftop-cinema',
    title: 'Rooftop cinema club',
    type: 'Film & outdoors',
    venue: 'Skyline Terrace · Hinjawadi',
    time: 'Sunday, 6:30 PM',
    location: 'Hinjawadi, Pune',
    price: 550,
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85',
    description: 'A classic film under an open sky, paired with soft blankets and cinema snacks. Arrive before sunset to settle in and catch the golden-hour view.',
    category: 'outdoors',
    day: 'weekend',
    rating: 4.8,
    rating_count: 42,
  },
  'brunch-social': {
    id: 6,
    slug: 'brunch-social',
    title: 'Sunday brunch social',
    type: 'Food & drinks',
    venue: 'Common Table · Pimpri',
    time: 'Sunday, 12:30 PM',
    location: 'Pimpri, Pune',
    price: 599,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=85',
    description: 'A leisurely afternoon meal designed for good conversation and new connections. Your ticket includes a shared seasonal menu and a welcome drink.',
    category: 'food',
    day: 'weekend',
    rating: 4.7,
    rating_count: 23,
  },
  'sunrise-run': {
    id: 7,
    slug: 'sunrise-run',
    title: 'Community sunrise run',
    type: 'Move',
    venue: 'Riverside Track · Punawale',
    time: 'Sunday, 6:00 AM',
    location: 'Punawale, Pune',
    price: 0,
    image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=85',
    description: 'Start the day with an easy, all-level community run. No pace pressure—just fresh air, friendly faces, and a stretch session after the finish.',
    category: 'move',
    day: 'today',
    rating: 5.0,
    rating_count: 18,
  },
};

export const HERO_TAGLINES = [
  'Your city is full of stories',
  'Discover what’s happening near you',
  'Unforgettable nights start here',
  'Curated plans for curious minds',
  'Find your rhythm in the city',
  'Never run out of things to do',
  'Experiences worth getting out for',
  'From secret gigs to rooftop nights',
  'Your weekend plans, sorted',
  'Fresh vibes, great people',
  'Step out and feel the energy',
  'Memories waiting to be made',
  'Live music, comedy, art & more',
  'The best of your city, all in one place',
  'Make every plan feel alive',
  'Catch tonight’s best experiences',
  'Explore hidden spots and vibrant scenes',
];
